authentication/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required as x

from .views import *

urlpatterns = [
    url(r"signup/$", SignUpView.as_view(), name="signup"),
    url(r"signin/$", SigninView.as_view(), name="signin"),
    url(r"socauth/$", SocAuthView.as_view(), name="socauth"),
    url(r"signout/$", x(SignoutView.as_view()), name="signout"),
    url(r"profile/$", x(ProfileView.as_view()), name='profile'),

    url(r"activeX/(?P<token>[\w\W]+)/$", ActivationView.as_view(), name="activate"),
    url(r"password/((?P<token>[\w\W]+)/)?$", PasswordUpdateView.as_view(), name="password"),
    url(r"newsletter/$", NewsLetterView.as_view(), name="newsletter"),

    # url(r"messageto/(?P<token>[\w\d]+)/((?P<prt>[\d])/(?P<ppk>[\d]+)/)?$", x(MessageTo.as_view()), name="message_to"),

    # MESSAGING
    url(r"messages/((?P<thread>[\d]+)/)?$", x(MessageView.as_view()), name="messages"),
]

blog/urls.py
from django.conf.urls import url

from .views import *

urlpatterns = [
    url(r"^$", ArticleListView.as_view(), name="list"),
    url(r"^(?P<page_name>[-\w\W]+)/$", ArticleView.as_view(), name="page"),
]

handcrafted/urls.py
from django.conf.urls import url
from django.conf.urls import include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from ajax_select import urls as ajax_select_urls
from django.conf import settings
from django.views.generic import TemplateView
from django.contrib.sitemaps.views import sitemap

from common.views import ShortenerView
from .views import LandingView, upload
from .sitemaps import HourlySiteMap, ProductSiteMap, ArticleSiteMap

sitemaps = {
    "index": HourlySiteMap,
    "products": ProductSiteMap,
    "posts": ArticleSiteMap,
}

handler404 = "handcrafted.views.handler404"
handler500 = "handcrafted.views.handler500"

urlpatterns = [
    url("^$", LandingView.as_view(), name="landing"),

    url(r"^store/", include("shop.urls", namespace="shop")),

    url(r"^(?P<code>[\w\W]{1,3})/$", ShortenerView.as_view(), name='shortener'),

    url(r"^common/", include("common.urls", namespace="common")),

    url(r"^selling/", include("selling.urls", namespace="selling")),

    url(r"^baseket/", include("basket.urls", namespace="basket")),

    url(r"^checkout/", include("checkout.urls", namespace="checkout")),

    url(r'^auth/', include("authentication.urls", namespace="auth")),

    url(r'^pages/', include("blog.urls", namespace="blog")),

    url(r'^calipso/', include("calipso.urls", namespace="calipso")),

    # MERGE AJAXABLE TO COMMON
    url(r'^ajaxable/', include("ajaxable.urls", namespace="ajaxable")),

    # UPLOAD VIEW
    url(r'^upload/$', upload, name="upload"),

    url(r"^ajax_select/", include(ajax_select_urls)),

    url(r'^admin/', admin.site.urls),

    url(r'^i18n/', include('django.conf.urls.i18n')),

    url(r'^tinymce/', include('tinymce.urls')),

    # ROBOTS AND SITEMAP
    url(r'^robots\.txt$', TemplateView.as_view(template_name="robots.txt")),

    url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) +\
static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if 'rosetta' in settings.INSTALLED_APPS:
    urlpatterns += [url(r'^admin/translate/', include('rosetta.urls')),]

templates/partials/comments.html
{% load i18n %}

{% if user.is_authenticated %}
<div class="row row-comment">
  <form method="POST" action=".">
    {% csrf_token %}
    <textarea class="form-control" name='comment'></textarea><br>
    <button type="submit" class="btn btn-default" type="submit">
      {% trans "კომენტარის დატოვება" %}
    </button>
  </form>
  {% else %}
    <p>
      <a href="{% url 'auth:signin' %}?next={{request.path}}">
        {% trans "გაიარე ავტორიზაცია" %}
      </a>
      {% trans "კომენტარის დასატოვებლად" %}</p>
  {% endif %}

  <hr>

  {% for review in object.reviews.all %}
    <div class="comment-container">
      {{review.content}}<br><br>
      <div class="pull-right comment-meta">
        {{review.created}}
      </div>
      <div class="pull-left comment-meta">
        {{review.author}}
      </div>
    </div>
  {% endfor %}

</div>

templates/partials/map.html
<div style="height:300px;" id="map"></div>

{% block scripts %}
<script>
  var map = null;
  var marker = null;
  var geocoder = null;

  $(document).ready(function(){
    $("#id_line1").on("change", get_address);
    $("#id_line2").on("change", get_address);
    $("#id_line3").on("change", get_address);
  });

  function initMap(){
    latitude = $('#id_lat').val();
    longitude = $("#id_lng").val();
    if (latitude.length == 0) latitude=41.7
    if (longitude.length == 0) longitude=44.7
    initial = {
      center: {lat:parseFloat(latitude), lng:parseFloat(longitude)},
      zoom: 9
    }
    map = new google.maps.Map(document.getElementById("map"), initial);
    if (latitude != 41.7 && longitude != 44.7){
      set_marker(parseFloat(latitude), parseFloat(longitude));
      map.setZoom(15);
    }
    geocoder = new google.maps.Geocoder;
  }

  function get_address(){
    if (geocoder != null){
      console.log("changed");
      address = $("#id_line1").val() + " ";
      address += $("#id_line2").val() + " ";
      address += $("#id_line3").val();
      get_coords(address);
    }
  }

  function set_marker(lat, lng){
    if (marker != null)
      marker.setMap(null);
    marker = new google.maps.Marker({
      position: {lat, lng},
      map: map
    });
  }

  function get_coords(address){
    geocoder.geocode({"address": address}, function(results, status){
      if (status == "OK"){
        map.setZoom(15);
        map.setCenter(results[0].geometry.location);
        set_marker(results[0].geometry.location.lat(),
          results[0].geometry.location.lng());
        $("#id_lat").val(results[0].geometry.location.lat());
        $("#id_lng").val(results[0].geometry.location.lng());
      } else {
        console.log("STATUS - ", status);
      }
    });
  }

</script>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyArOqECLO1OY8YM92XHRelMR0G4uxF6-qE&callback=initMap" async defer></script>
{% endblock %}

templates/partials/messages.html
<div class="{% if not messages %}message-ajaxable-hide{% else %}message-ajaxable{% endif %}">
  {% for message in messages %}
    <div class="{{message.tags}} message-content">{{message}}</div>
  {% empty %}
    <div class="success message-content"></div>
  {% endfor %}
</div>

{% block scripts %}
<script>
  $(document).ready(function(){
    setTimeout(hide_messsage, 3000);
  });
</script>
{% endblock %}

templates/partials/navigation.html
{% load i18n %}

<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/">handX</a>
        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li>
                    <a href="{% url 'shop:main' %}">
                      {% trans "ნივთები" %}
                    </a>
                </li>
                {% if user.is_authenticated %}
                <li>
                  <a href="{% url 'auth:profile' %}">
                    {% trans "კალათა" %}
                  </a>
                </li>
                {% else %}
                <li>
                  <a href="{% url 'auth:signin' %}">
                    {% trans "ავტორიზაცია" %}</a>
                  </a>
                </li>
                <li>
                  <a href="{% url 'auth:signup' %}">
                    {% trans "რეგისტრაცია" %}
                  </a>
                </li>
                {% endif %}
                <li>
                    <a href="{% url 'common:sp' name='aboutus' %}">
                      {% trans "ჩვენს შესახებ" %}
                    </a>
                </li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
              <li>
                <a href="{% url 'shop:list' %}"
                  <i class="fa fa-search" aria-hidden="true"></i>
                </a>
              </li>
              <li>
                {% if user.get_seller != None and user.is_staff %}
                  <a href="{% url 'admin:shop_product_changelist' %}">
                    {% trans "მართე პროდუქტები" %}
                  </a>
                {% else %}
                  <a href="{% url 'selling:start' %}">
                    {% trans "გაყიდე handx-ზე" %}
                  </a>
                {% endif %}
              </li>
            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container -->
</nav>

templates/partials/search.html
{% load i18n %}

<div class="row row-search">
  <div class="col-lg-12">
    <div class="input-group">
      <input id="searchBox" value="{{query}}" type="text" class="form-control" placeholder="{% trans 'მოძებნე...' %}">
      <span class="input-group-btn">
        <button onclick="search()" class="btn btn-accent btn-search" type="button">
          {% trans "მოძებნე" %}
        </button>
      </span>
    </div>
  </div>
</div>

<script>
  function search(){
    value = $("#searchBox").val();
    var url = "";
    if (value.length != 0 ){
      if (window.location.href.indexOf("?query") > 0)
        url = window.location.href.split("?query")[0]
      else
        url = window.location.href
      window.location.href = url + "?query=" + value;
    }
  }
</script>

templates/partials/start_selling.html
{% load i18n %}

<div class="row">
  <div class="page-header" style="margin-left: 15px;">
    <h4><strog>{% trans "რას გთავაზობთ?" %}</strong></h4>
  </div>
  <ul>
    <li>{% trans "sluts like hell" %}</li>
    <li>{% trans "good beer" %}</li>
    <li>{% trans "and blowjob, like never before" %}</li>
  </ul><br>

  <div class="page-header" style="margin-left: 15px;">
    <h4><strog>{% trans "რა არის საჭირო?" %}</strong></h4>
  </div>
  <ul>
    <li>{% trans "რახან გინდა გაყიდვა" %}</li>
    <li>{% trans "გაქვს პირადობის მოწმობა" %}</li>
    <li>{% trans "და ქმნი სელნაკეთ ნივთებს" %}</li>
    <li>{% trans "ჩვენ მხოლოდ სამი ველი გვინდა :)" %}</li>
  </ul><br>
</div>

templates/partials/word_cloud.html
{% load static %}

{% block head %}
  <link href="{% static 'css/wordCloud.css' %}" rel="stylesheet">
{% endblock %}

<div class="row">
  <ul class="word-cloud">
    {% for word in wordcloud %}
      <li class="word-cloud__word word-cloud__word--{{word.count}}">
        <a href={% url "calipso:psearch" query=word.word %}>
          {{word}}
        </a>
      </li>
    {% endfor %}
  </ul>
</div>