authentication/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required as x

from .views import *

urlpatterns = [
    url(r"signup/$", SignUpView.as_view(), name="signup"),
    url(r"signin/$", SigninView.as_view(), name="signin"),
    url(r"socauth/$", SocAuthView.as_view(), name="socauth"),
    url(r"signout/$", x(SignoutView.as_view()), name="signout"),
    url(r"profile/$", x(ProfileView.as_view()), name='profile'),

    url(r"activeX/(?P<token>[\w\W]+)/$", ActivationView.as_view(), name="activate"),
    url(r"password/((?P<token>[\w\W]+)/)?$", PasswordUpdateView.as_view(), name="password"),
    url(r"newsletter/$", NewsLetterView.as_view(), name="newsletter"),

    # url(r"messageto/(?P<token>[\w\d]+)/((?P<prt>[\d])/(?P<ppk>[\d]+)/)?$", x(MessageTo.as_view()), name="message_to"),

    # MESSAGING
    url(r"messages/((?P<thread>[\d]+)/)?$", x(MessageView.as_view()), name="messages"),
]

blog/urls.py
from django.conf.urls import url

from .views import *

urlpatterns = [
    url(r"^$", ArticleListView.as_view(), name="list"),
    url(r"^(?P<page_name>[-\w\W]+)/$", ArticleView.as_view(), name="page"),
]

handcrafted/urls.py
from django.conf.urls import url
from django.conf.urls import include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from ajax_select import urls as ajax_select_urls
from django.conf import settings
from django.views.generic import TemplateView
from django.contrib.sitemaps.views import sitemap

from common.views import ShortenerView
from .views import LandingView, upload
from .sitemaps import HourlySiteMap, ProductSiteMap, ArticleSiteMap

sitemaps = {
    "index": HourlySiteMap,
    "products": ProductSiteMap,
    "posts": ArticleSiteMap,
}

handler404 = "handcrafted.views.handler404"
handler500 = "handcrafted.views.handler500"

urlpatterns = [
    url("^$", LandingView.as_view(), name="landing"),

    url(r"^store/", include("shop.urls", namespace="shop")),

    url(r"^(?P<code>[\w\W]{1,3})/$", ShortenerView.as_view(), name='shortener'),

    url(r"^common/", include("common.urls", namespace="common")),

    url(r"^selling/", include("selling.urls", namespace="selling")),

    url(r"^baseket/", include("basket.urls", namespace="basket")),

    url(r"^checkout/", include("checkout.urls", namespace="checkout")),

    url(r'^auth/', include("authentication.urls", namespace="auth")),

    url(r'^pages/', include("blog.urls", namespace="blog")),

    url(r'^calipso/', include("calipso.urls", namespace="calipso")),

    # MERGE AJAXABLE TO COMMON
    url(r'^ajaxable/', include("ajaxable.urls", namespace="ajaxable")),

    # UPLOAD VIEW
    url(r'^upload/$', upload, name="upload"),

    url(r"^ajax_select/", include(ajax_select_urls)),

    url(r'^admin/', admin.site.urls),

    url(r'^i18n/', include('django.conf.urls.i18n')),

    url(r'^tinymce/', include('tinymce.urls')),

    # ROBOTS AND SITEMAP
    url(r'^robots\.txt$', TemplateView.as_view(template_name="robots.txt")),

    url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) +\
static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if 'rosetta' in settings.INSTALLED_APPS:
    urlpatterns += [url(r'^admin/translate/', include('rosetta.urls')),]

shop/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required as lr

from rest_framework.urlpatterns import format_suffix_patterns

from .views import *


urlpatterns = [
    url(r"^$", MainView.as_view(), name='main'),
    url(r"seller/(?P<slug>[-\w\W]+)/$", SellerView.as_view(), name="seller"),
    url(r"products/$", ProductListView.as_view(), name="list"),
    url(r"products/((?P<token>[\w\W]+)/)?$", ProductListView.as_view(), name="deserialize"), #for what is used?
    url(r"keyword/(?P<pk>[\d]+)/$", KeyWordProductListView.as_view(), name="keyword_products"),

    url(r"product/(?P<slug>[\w\W]+)/$", ProductView.as_view(), name="product"),

    url(r"search/$", SearchView.as_view(), name="search"),

    url(r"acceptSpecial/(?P<token>[\w\W]+)/$", lr(AcceptSpecialView.as_view()), name="accept_special"),

    url(r"product_serialize/(?P<pk>[0-9]+)/$", ProductSerializerView.as_view(), name="serialize_product"),
]

urlpatterns = format_suffix_patterns(urlpatterns)

common/models.py
import ast
from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.core.urlresolvers import reverse
from django.core.urlresolvers import resolve
from django.utils.translation import get_language

from .helpers import gen_code, generate_token_ft

class SnapShot(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


class Slide(models.Model):
    SPC = (
        ("0", _("მთავარი გვერდი top")),
    )

    position = models.CharField(_("სლაიდის პოზიცია"), max_length=1, choices=SPC, default="0")

    image = models.ImageField(upload_to="slide_images", height_field='img_height', width_field='img_width', null=True)
    img_height = models.PositiveIntegerField(blank=True)
    img_width = models.PositiveIntegerField(blank=True)

    caption_url = models.CharField(_("მცირე ტექსტის ბმული"), max_length=64, blank=True, default="#")
    action_url = models.CharField(_("სამოქმედო ბმული"), max_length=64, blank=True)
    caption_text_ka = models.CharField(_("მცირე ტექსტი (ka)"), max_length=32, blank=True, default="#")
    caption_text_en = models.CharField(_("მცირე ტექსტი (en)"), max_length=32, blank=True, default="#")
    caption_text_ru = models.CharField(_("მცირე ტექსტი (ru)"), max_length=32, blank=True, default="#")
    action_text_ka = models.CharField(_("სამოქმედო ტექსტი (ka)"), max_length=32, blank=True)
    action_text_en = models.CharField(_("სამოქმედო ტექსტი (en)"), max_length=32, blank=True)
    action_text_ru = models.CharField(_("სამოქმედო ტექსტი (ru)"), max_length=32, blank=True)
    main_text_ka = models.CharField(_("მთავარი ტექსტი (ka)"), max_length=32, blank=True)
    main_text_en = models.CharField(_("მთავარი ტექსტი (en)"), max_length=32, blank=True)
    main_text_ru = models.CharField(_("მთავარი ტექსტი (ru)"), max_length=32, blank=True)

    @property
    def caption_text(self):
        fname = "caption_text_" + get_language()
        attr = getattr(self, fname, None)
        return attr if attr else self.caption_text_ka

    @property
    def action_text(self):
        fname = "action_text_" + get_language()
        attr = getattr(self, fname, None)
        return attr if attr else self.action_text_ka
    
    @property
    def main_text(self):
        fname = "main_text_" + get_language()
        attr = getattr(self, fname, None)
        return attr if attr else self.main_text_ka

    def __str__(self):
        return "{0}:{1}".format(self.get_position_display(), self.main_text)

    class Meta:
        verbose_name = _("სლაიდი")
        verbose_name_plural = _('სლაიდერები')

class URLink(SnapShot):
    code = models.CharField(_("კოდი"), max_length=3, unique=True)
    rev = models.CharField(_("რევერს/ნორმ. url"), max_length=128)

    @staticmethod
    def get_shortcut(referer):
        entry, created = URLink.objects.get_or_create(rev=referer)
        if created:
            entry.save()
        return reverse("shortener", kwargs={"code": entry.code})

    def __str__(self):
        return self.rev

    def save(self, *args, **kwargs):
        if self.pk is None:
            code = None
            try:
                while True:
                    code = gen_code()
                    URLink.objects.get(code=code)
            except URLink.DoesNotExist:
                self.code = code
        super().save(*args, **kwargs)

    class Meta:
        verbose_name = _("შემოკლება")
        verbose_name_plural = _("შემოკლებები")
        ordering = ['-created']


class Tokenizer(models.Model):
    token = models.CharField(max_length=24, default=generate_token_ft, db_index=True)
    meta = models.TextField(blank=True, default="")

    @staticmethod
    def get_new_token(obj=False):
        if not obj:
            return Tokenizer.objects.create().token
        return Tokenizer.objects.create()

    @staticmethod
    def get_token(token):
        try:
            return Tokenizer.objects.get(token=token)
        except Tokenizer.DoesNotExist:
            return None

    @staticmethod
    def check_token(token):
        if Tokenizer.objects.filter(token=token).count():
            return True
        return False

    def update(self, **kwargs):
        # updates token meta dict by kwargs
        initial = ast.literal_eval(self.meta)
        initial.update(**kwargs)
        self.meta = str(initial)
        self.save()

    def get_val(self, vname):
        # get value by name from meta dict
        data = ast.literal_eval(self.meta)
        return data[vname] if vname in data else None

    def expire(self):
        self.delete() # mark token to delete it

    def get_products_link(self):
        return URLink.get_shortcut(reverse("shop:deserialize", kwargs={"token": self.token}))

    def get_token_title(self):
        try:
            return self.get_val("title")
        except Exception:
            return "CONVERSION ERROR"
    get_token_title.short_description = _("თოუქენის სათაური")

    def __str__(self):
        return self.token

    def save(self, *args, **kwargs):
        if self.pk is None:
            self.meta = "{}"
        super().save(*args, **kwargs)


class Image(models.Model):
    image = models.ImageField(verbose_name=_("სურათი"), upload_to="uploads", height_field='img_height', width_field='img_width', null=True, blank=True)
    img_height = models.PositiveIntegerField(blank=True, null=True)
    img_width = models.PositiveIntegerField(blank=True, null=True)

    def get_absolute_url(self):
        return self.image.url

    def __str__(self):
        return "Image N{0}".format(self.pk)

    class Meta:
        verbose_name = _("სურათი")
        verbose_name_plural = _("სურათები")

class Keyword(models.Model):
    name = models.CharField(_("სიტყვა"), max_length=32)
    fname = models.CharField(_("არაქართული ანალოგი"), max_length=32, blank=True, default="")
    base = models.CharField(_("ფუძე"), max_length=512, blank=True, default="")
    # relatives = models.CharField(_("ნათესავები"), max_length=512, blank=True, default="")
    # meta = models.CharField(_("მეტა ინფორმაცია"), max_length=128, blank=True, default="")

    def get_absolute_url(self):
        return reverse("shop:keyword_products", kwargs={"pk": self.pk})

    def __str__(self):
        return self.name if get_language() == "ka" else self.fname

    def save(self, *args, **kwargs):
        # ხმოვნით დაბოლოებული სიტყვა - მ, თანხმოვნით - მა
        if len(self.name) > 3:
            self.base = self.name + self.name[:-1] + self.name[:-2]
        super().save(*args, **kwargs)

    class Meta:
        verbose_name = _("საკვანძო სიტყვა")
        verbose_name_plural = _("საკვანძო სიტყვები")

shop/forms.py
from django import forms
from django.utils.translation import ugettext_lazy as _
from ajax_select.fields import AutoCompleteSelectMultipleField
from django.utils import timezone

from tinymce.widgets import TinyMCE
from .models import Product
from common.models import Keyword

ATS = {"class":"form-control", "required":"required"}

class ProductForm(forms.ModelForm):
    name = forms.CharField(widget=forms.TextInput(attrs=ATS),
        label=_("პროდუქტის დასახელება"))
    desc = forms.CharField(widget=TinyMCE(attrs=ATS),
        label=_("პროდუქტის აღწერა"))
    price = forms.DecimalField(widget=forms.NumberInput(attrs=ATS),
        label=_("პროდუქტის ფასი (ლარი)"))
    quantity = forms.IntegerField(widget=forms.NumberInput(attrs=ATS),
        label=_("პროდუქტის რაოდენობა"))

    class Meta:
        model = Product
        exclude = ("images", "tax", "rank",)

class ProductAdminForm(forms.ModelForm):
    keywords = AutoCompleteSelectMultipleField("keywords", label=_("საკვანძო სიტყვები"), required=False, help_text=_("შეიყვანეთ საძიებო სიტყვა, ან დაამატეთ"))
    raw = forms.CharField(widget=forms.HiddenInput(), required=False)

    def get_raw_keywords(self):
        keywords = Keyword.objects.none()
        if len(self.cleaned_data['raw']) == 0:
            return Keyword.objects.none();
        for pk in self.cleaned_data['raw'].split("|"):
            keywords |= Keyword.objects.filter(pk=pk)
        return keywords

    def clean_keywords(self):
        keyword_pks = self.cleaned_data['keywords']
        for pk in keyword_pks:
            target = Keyword.objects.get(pk=pk)
            if Keyword.objects.filter(name=target.name, fname=target.fname).count() > 1:
                raise forms.ValidationError(_("საკვანძო სიტყვებში აღმოჩენილია 2 ან მეტი მსგავსი სიტყვა"),
                    code="invalid")
        return self.cleaned_data['keywords']

    class Meta:
        model = Product
        fields = ("__all__")

    
    class Media:
        js = ("js/admin/product_management.js", )

templates/shop/generic_product_item.html
{% load i18n static thumbnail %}

<div class="{{classes}}">
  <figure class="snip1091">
    {% thumbnail object.first_image "600x360" crop="center" as th %}
      <img src="{{th.url}}" alt="image"/>
    {% endthumbnail %}
    <figcaption>
      <h2>{{object.get_sname}}</h2>
    </figcaption>
    <a href="{{object.get_absolute_url}}"></a>
  </figure>
</div>

templates/shop/mp_product_item.html
{% load i18n static thumbnail %}

<div class="col-sm-6 {% if not rmmd4 %} col-md-4 {% endif %}">
  <figure class="snip1091">
    {% thumbnail object.first_image "390x300" crop="0%" as th %}
      <img src="{{th.url}}" alt="image"/>
    {% endthumbnail %}
    <figcaption>
      <h2>{{object.get_sname}}</h2>
    </figcaption>
    <a href="{{object.get_absolute_url}}"></a>
  </figure>
</div>

templates/shop/product_detail.html
{% extends "base.html" %}
{% load i18n static thumbnail %}

{% block title %}
  {{object.title}}
{% endblock %}

{% block content %}

  <div class="row row-petite">

    <div class="page-header">
      <h4>{{object.name}}</h4>
      <h6>
        {% with seller=object.get_seller %}
          <a href="{% url 'selling:page' token=seller.account.token %}" class="blink">
            {{seller.shopName}}
          </a>
        {% endwith %}
      </h6>
    </div>

    <div class="col-sm-8">
      {% thumbnail object.first_image '400x400' crop="center" as th %}
        <img id="main-holder" src="{{th.url}}" class="img-responsive img-product">
      {% endthumbnail %}

      <div style="margin-top: 5px;text-align:center;">
        {% for image in object.image_set.all %}
          {% thumbnail image.image "400x400" crop="center" as th %}
            <img class="img-responsive img-prod-detail" onmouseover="update_image(this)"
              src="{{th.url}}">
          {% endthumbnail %}
        {% endfor %}
      </div>
    </div>

    <div class="col-sm-4">
      {{object.desc|safe}}
      {% if user.is_authenticated %}
        <button class="btn btn-default btn-like" id="upvote" args="{'ppk': {{object.pk}}, 'u': '{{user.pk}}'}" >
          <i class="fa fa-heart-o" aria-hidden="true"></i>
          {% trans "მომწონს" %}
          <span id="votes" class="badge">{{object.rank}}</span>
        </button>
      {% else %}
        <a class="btn btn-default btn-like" href="{% url 'auth:signin' %}?next={{request.path}}">
          <i class="fa fa-heart-o" aria-hidden="true"></i>
          {% trans "მომწონს" %}
          <span id="votes" class="badge">{{object.rank}}</span>
        </a>
      {% endif %}
    </div>
  </div>

  <div class="row row-petite">
    <div class="page-header">
      <h4>{% trans "ვარიანტები" %}</h4>
    </div>
    <div class="btn-group">
      {% for option in object.productoption_set.all %}
        {% if user.is_authenticated %}
          <a class="btn btn-default btn-basket" onclick="addtobasket_ajaxable()" args="{'bpk': {{user.basket.pk}}, 'opk': {{option.pk}}, 'quantity':1}">
            <i class="fa fa-cart-plus" aria-hidden="true"></i>
            <span style="margin-left: 5px;"></span>
            {{option.get_sname}} GEL{{option.get_price}}
          </a>
        {% else %}
          <a class="btn btn-default btn-basket" href="{% url 'auth:signin' %}?next={{request.path}}">
            <i class="fa fa-cart-plus" aria-hidden="true"></i>
            {{option.get_sname}} GEL{{option.get_price}}
          </a>
        {% endif %}
      {% endfor %}
    </div>
  </div>

  <div class="row row-petite">

  {# SIMILAR PRODUCTS BLOCK #}
    <div class="page-header">
      <h4>{% trans "შეიძლება ასევე მოგეწონოს" %}</h4>
    </div>

    {% for object in relatives %}
      {% include 'shop/related_product_item.html' %}
    {% endfor %}
  </div>

  <div class="row row-petite">
  {# COMMENTS #}
    <div class="page-header">
      <h4>{% trans "დატოვე კომენტარი" %}</h4>
    </div>
    {% include 'partials/comments.html' %}
  </div>

{% endblock %}

{% block scripts %}

  <script>
    var lastElem = null;
    function update_image(element){
      $("#main-holder").attr("src", $(element).attr("src"));
      $(element).addClass("active");
      $(lastElem).removeClass("active");
      lastElem = element;
    }

    //AJAXABLE TEST CODE
    $("#upvote").on("click", function(event){
      ajaxable("upvote", event, function(result){
        $("#votes").text(result);
      });
    });

    function addtobasket_ajaxable(){
      ajaxable("addtobasket", event, function(result){
        show_message(result);
      });
    }

    $("#shortcut").on("click", function(event){
      ajaxable("shortcut", event, function(result){
        slink = window.location.host + result;
      });
    });
    // END OF THE TEST CODE
  </script>
{% endblock %}

templates/shop/product_item_v1.html
{% load i18n thumbnail static %}

<div class="col-product">
  <a href="{{item.get_absolute_url}}">
    {% thumbnail item.first_image "300x200" crop="center" as th %}
      <img class="img-responsive img-product" src="{{th.url}}">
    {% endthumbnail %}
  </a>
  <div class="title">
    <a href="{{item.get_absolute_url}}">
      {{item.get_sname}}
    </a>
  </div>
  <div class="content">
    {{item.desc|safe}}
  </div>
  <a href="{% url 'selling:page' token=item.get_seller.account.token %}" class="action left">
    <i class="fa fa-user" aria-hidden="true"></i>
  </a>
  <a class="action right">
    <i class="fa fa-shopping-cart" aria-hidden="true"></i>
  </a>
</div>

templates/shop/product_list.html
{% extends "base.html" %}
{% load i18n static thumbnail %}

{% block title %}
  {% trans "Store" %}
{% endblock %}

{% block content %}

{% if searchable %}
  {% include 'partials/search.html' %}
{% endif %}

{% if sellable %}
  {% include 'selling/partials/seller.html' %}
{% endif %}

<div class="row">
  {% for object in object_list %}
    {% include 'shop/mp_product_item.html' %}
  {% endfor %}
</div>

{% endblock %}

{% block scripts %}
<script>
  $(document).ready(function(){
    cols = ['red', 'green', 'navy', 'blue']
    $.each($("figure"), function(i, element){
      cname = cols[Math.floor(Math.random()*cols.length)];
      $(element).addClass(cname);
    });
  });

  $("figure").mouseleave(function() {
      $(this).removeClass("hover");
    });
</script>
{% endblock %}

templates/shop/rel_product_item.html
{% load i18n static thumbnail %}

<div class="col-sm-6">
  <figure class="snip1091">
    {% thumbnail object.first_image "390x300" crop="0%" as th %}
      <img src="{{th.url}}" alt="image"/>
    {% endthumbnail %}
    <figcaption>
      <h2>{{object.get_sname}}</h2>
    </figcaption>
    <a href="{{object.get_absolute_url}}"></a>
  </figure>
</div>

templates/shop/related_product_item.html
{% load i18n static thumbnail %}

<div class="col-sm-6 col-xs-6">
  <figure class="snip1091">
    {% thumbnail object.first_image "390x300" crop="0%" as th %}
      <img src="{{th.url}}" alt="image" class="img-responsive"/>
    {% endthumbnail %}
    <figcaption>
      <h4>{{object.get_sname}}</h4>
    </figcaption>
    <a href="{{object.get_absolute_url}}"></a>
  </figure>
</div>