authentication/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required as x

from .views import *

urlpatterns = [
    url(r"signup/$", SignUpView.as_view(), name="signup"),
    url(r"signin/$", SigninView.as_view(), name="signin"),
    url(r"socauth/$", SocAuthView.as_view(), name="socauth"),
    url(r"signout/$", x(SignoutView.as_view()), name="signout"),
    url(r"profile/$", x(ProfileView.as_view()), name='profile'),

    url(r"activeX/(?P<token>[\w\W]+)/$", ActivationView.as_view(), name="activate"),
    url(r"password/((?P<token>[\w\W]+)/)?$", PasswordUpdateView.as_view(), name="password"),
    url(r"newsletter/$", NewsLetterView.as_view(), name="newsletter"),

    # url(r"messageto/(?P<token>[\w\d]+)/((?P<prt>[\d])/(?P<ppk>[\d]+)/)?$", x(MessageTo.as_view()), name="message_to"),

    # MESSAGING
    url(r"messages/((?P<thread>[\d]+)/)?$", x(MessageView.as_view()), name="messages"),
]

blog/urls.py
from django.conf.urls import url

from .views import *

urlpatterns = [
    url(r"^$", ArticleListView.as_view(), name="list"),
    url(r"^(?P<page_name>[-\w\W]+)/$", ArticleView.as_view(), name="page"),
]

handcrafted/urls.py
from django.conf.urls import url
from django.conf.urls import include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from ajax_select import urls as ajax_select_urls
from django.conf import settings
from django.views.generic import TemplateView
from django.contrib.sitemaps.views import sitemap

from common.views import ShortenerView
from .views import LandingView, upload
from .sitemaps import HourlySiteMap, ProductSiteMap, ArticleSiteMap

sitemaps = {
    "index": HourlySiteMap,
    "products": ProductSiteMap,
    "posts": ArticleSiteMap,
}

handler404 = "handcrafted.views.handler404"
handler500 = "handcrafted.views.handler500"

urlpatterns = [
    url("^$", LandingView.as_view(), name="landing"),

    url(r"^store/", include("shop.urls", namespace="shop")),

    url(r"^(?P<code>[\w\W]{1,3})/$", ShortenerView.as_view(), name='shortener'),

    url(r"^common/", include("common.urls", namespace="common")),

    url(r"^selling/", include("selling.urls", namespace="selling")),

    url(r"^baseket/", include("basket.urls", namespace="basket")),

    url(r"^checkout/", include("checkout.urls", namespace="checkout")),

    url(r'^auth/', include("authentication.urls", namespace="auth")),

    url(r'^pages/', include("blog.urls", namespace="blog")),

    url(r'^calipso/', include("calipso.urls", namespace="calipso")),

    # MERGE AJAXABLE TO COMMON
    url(r'^ajaxable/', include("ajaxable.urls", namespace="ajaxable")),

    # UPLOAD VIEW
    url(r'^upload/$', upload, name="upload"),

    url(r"^ajax_select/", include(ajax_select_urls)),

    url(r'^admin/', admin.site.urls),

    url(r'^i18n/', include('django.conf.urls.i18n')),

    url(r'^tinymce/', include('tinymce.urls')),

    # ROBOTS AND SITEMAP
    url(r'^robots\.txt$', TemplateView.as_view(template_name="robots.txt")),

    url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) +\
static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if 'rosetta' in settings.INSTALLED_APPS:
    urlpatterns += [url(r'^admin/translate/', include('rosetta.urls')),]

authentication/forms.py
from django import forms
from django.utils.translation import ugettext_lazy as _
from django.core.validators import RegexValidator
from .models import *

ATS = {"class": "form-control", "required": "required"}

class AccountForm(forms.ModelForm):
    email = forms.EmailField(widget=forms.TextInput(attrs=ATS),
        label=_("ელ.ფოსტა"))
    name = forms.CharField(widget=forms.TextInput(attrs=ATS),
        label=_("სახელი და გვარი"))
    phone = forms.CharField(widget=forms.TextInput(attrs=ATS),
        label=_("ტელეფონის ნომერი (xxx-xxx-xxx)"), validators=(
        RegexValidator(r"[\d]{3}-[\d]{3}-[\d]{3}", message=_(
        "არასწორი ნომრის ფორმატი")),))
    password = forms.CharField(widget=forms.PasswordInput(attrs=ATS),
        label=_("პაროლი"))

    class Meta:
        model = Account
        fields = ("name", "phone", "email", "password",)
        exclude = ("is_active", "is_admin", "is_staff", "last_login", "basket",
            "perms", "address",)

class AccountUpdateForm(AccountForm):
    email = None
    password = None

    age = forms.IntegerField(widget=forms.NumberInput(attrs=ATS),
        label=_("ასაკი"))
    sex = forms.ChoiceField(widget=forms.Select(attrs=ATS),
        label=_("სქესი"), choices=ASC)

    class Meta:
        model = Account
        fields = ("name", "phone", "age", "sex")

authentication/views.py
from django.http import JsonResponse
from django.shortcuts import render
from django.shortcuts import redirect
from django.core.urlresolvers import reverse
from django.shortcuts import get_object_or_404
from django.views import generic
from django.contrib.auth import authenticate
from django.contrib.auth import logout
from django.contrib.auth import login
from django.contrib import messages

from django.utils.translation import ugettext_lazy as _

from shop.models import Product
from .models import *
from .forms import *

NOT_ACTIVE_MESSAGE = _("თქვენი ანგარიში არ არის აქტიური, მიყევით ბმულს ელ.ფოსტაზე")
BAD_CREDENTIALS = _("თქვენს მიერ შეყვანილი მონაცემები არასწორია")
NO_ACCOUNT = _("მომხმარებელი არ არსებობს, გაიარეთ რეგისტრაცია :)")
SIGNUP_SUCCESS = _("თქვენ წარმატებით დარეგისტრირდით, გააქტიურეთ ანგარიში ბმულით ელ.ფოსტაზე")


# Create your views here.
class SignUpView(generic.CreateView):
    template_name = "authentication/signin.html"
    model = Account
    form_class = AccountForm
    object = None

    def dispatch(self, request, *args, **kwargs):
        if request.is_ajax():
            return self.ajax(request, *args, **kwargs)
        return super().dispatch(request, *args, **kwargs)

    def ajax(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            entry = form.save()
            entry.set_password(entry.password)
            entry.save()
            entry.send_activation_mail(request.META["HTTP_HOST"])
            messages.add_message(self.request, messages.SUCCESS, SIGNUP_SUCCESS)
            return JsonResponse({"redirect": reverse("landing")})
        else:
            return JsonResponse(form.errors.as_json(), safe=False)


class SigninView(generic.TemplateView):
    template_name = 'authentication/signin.html'

    def hook_next(self):
        if "QUERY_STRING" in self.request.META:
            qs = self.request.META['QUERY_STRING']
            if "next" in self.request.META['QUERY_STRING']:
                return self.request.META["QUERY_STRING"]
        return None

    def red_next(self):
        qs = self.hook_next()
        if qs is not None:
            return redirect(qs.replace("next=", ""))
        return redirect(reverse("auth:profile"))

    def dispatch(self, request, *args, **kwargs):
        if request.is_ajax():
            return self.ajax(request, *args, **kwargs)
        return super().dispatch(request, *args, **kwargs)

    def get_object(self, email=None):
        return Account.objects.filter(email=email).first()

    def ajax(self, request, *args, **kwargs):
        data = {}
        account = self.get_object(request.POST.get("email"))
        if not account:
            data['error'] = NO_ACCOUNT
        elif not account.is_active:
            data['error'] = NOT_ACTIVE_MESSAGE
        elif not account.check_password(request.POST.get("password")):
            data['error'] = BAD_CREDENTIALS
        else:
            login(request, account)
            data['redirect'] = self.red_next().url
        return JsonResponse(data)

    def post(self, request, *args, **kwargs):
        email = request.POST.get("email", "nomail@email.com")
        password = request.POST.get("password", "pswd")
        try:
            entry = Account.objects.get(email=email)
            if not entry.is_active:
                messages.add_message(request, messages.WARNING, NOT_ACTIVE_MESSAGE)
                return render(request, self.template_name,
                    self.get_context_data(**kwargs))
            entry = authenticate(username=email, password=password)
            if entry is not None:
                login(request, entry)
                return self.red_next()
            messages.add_message(request, messages.WARNING, BAD_CREDENTIALS)
        except Account.DoesNotExist:
            messages.add_message(request, messages.WARNING, NO_ACCOUNT)
        return render(request, self.template_name, self.get_context_data(**kwargs))

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['next'] = self.hook_next()
        context['form'] = AccountForm()
        return context


class SocAuthView(generic.TemplateView):
    
    def dispatch(self, request, *args, **kwargs):
        if request.is_ajax():
            return self.ajax(request, *args, **kwargs)
        return redirect("landing")

    def ajax(self, request, *args, **kwargs):
        name = request.GET.get("name", None)
        email = request.GET.get("email", None)
        fbid = request.GET.get("id", None)
        data = {"redirect": reverse("landing")}
        # start processing if all components are present
        if name and email and fbid:
            entry = None
            try:
                # check if same user exists
                entry = Account.objects.get(email=email)
                if entry.fbid != fbid:
                    entry.fbid = fbid
                entry.save()
            except Account.DoesNotExist:
                # if not below block is executed
                entry = Account.objects.create(email=email,
                    name=name, fbid=fbid, phone="", is_active=True)
                # password is not set @ all
            login(request, entry)
            data['redirect'] = reverse("auth:profile")
        return JsonResponse(data)


class ProfileView(generic.DetailView):
    template_name = "authentication/profile.html"
    object = None

    def get_object(self):
        return Account.objects.get(pk=self.request.user.pk)

    def post(self, request, *args, **kwargs):
        form = AccountUpdateForm(request.POST, instance=request.user)
        if form.is_valid():
            request.user.save()
            messages.add_message(request, messages.SUCCESS,
                str(_("თქვენი ინფორმაცია წარმატებით განახლდა")))
        else:
            messages.add_message(request, messages.WARNING,
                str(_("ინფორმაციის განახლება ვერ მოხერხდა")))
        return redirect("auth:profile")


    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['updateForm'] = AccountUpdateForm(instance=self.object)
        print(self.request.user.basket.is_empty())
        return context

class SignoutView(generic.RedirectView):
    def get(self, request, *args, **kwargs):
        logout(request)
        messages.add_message(request, messages.WARNING,
            _("თქვენ გახვედით ვებ გვერდიდან, გელით უკან :)"))
        return redirect(reverse("landing"))

class ActivationView(generic.RedirectView):
    def get(self, request, *args, **kwargs):
        object = get_object_or_404(Account, token=self.kwargs.get('token', None))
        object.is_active = True
        object.save()
        messages.add_message(request, messages.SUCCESS,
            str(_("თქვენი ანგარიში წარმატებით გააქტიურდა")))
        if authenticate(username=object.email, password=object.password):
            login(object, request)
            return redirect(reverse("auth:profile"))
        return redirect(reverse("auth:profile"))

class PasswordUpdateView(generic.TemplateView):
    template_name = "authentication/password.html"

    def post(self, request, *args, **kwargs):
        if request.POST.get("step_email", None):
            entry = None
            try:
                entry = Account.objects.get(email=request.POST.get("email", None))
            except Account.DoesNotExist:
                messages.add_message(request, messages.SUCCESS, 
                    str(_("სამწუხაროდ, მომხმარებელი ამ ელ.ფოსტით არ არის დარეგისტრირებული")))
                return redirect("auth:password")
            if entry:
                entry.send_reset_link(request.META["HTTP_HOST"])
                messages.add_message(request, messages.SUCCESS, str(_(
                    "ელ.ფოსტაზე გამოგიგზავნეთ პაროლის შესაცვლელი ბმული")))
                return redirect("landing")
        elif request.POST.get("step_password", None):
            token = kwargs.get("token", None)
            password = request.POST.get("password", None)
            entry = None
            print(request.POST, kwargs)
            try:
                entry = Account.objects.get(token=token)
            except Account.DoesNotExist:
                messages.add_message(request, messages.SUCCESS, str(_(
                    "პაროლის შესაცვლელი ბმული არასწორია")))
                return redirect("auth:password")
            if entry and password:
                entry.set_password(password)
                entry.save()
                messages.add_message(request, messages.SUCCESS, str(_(
                    "პაროლი წარმატებით შეიცვალა, გაიარეთ ავტორიზაცია")))
                return redirect(reverse("landing") + "#signin")
            elif not password:
                messages.add_message(request, messages.SUCCESS, str(_(
                    "გთხოვთ მიუთითოთ პაროლი")))
                return redirect("auth:password", kwargs={"token": entry.token})

    def get(self, request, *args, **kwargs):
        token = kwargs.get("token", None)
        print(Account.objects.filter(token=token))
        if token and not Account.objects.filter(token=token).count():
            messages.add_message(request, messages.SUCCESS, str(_(
                    "პაროლის შესაცვლელი ბმული არასწორია")))
        return render(request, self.template_name, self.get_context_data(
            step = 1 if kwargs.get("token", None) else 0))


class NewsLetterView(generic.RedirectView):
    def post(self, request, *args, **kwargs):
        email = request.POST.get("email", None)
        status = CollectedEmail.objects.get_or_create(email=email)[1]
        if status:
            messages.add_message(request, messages.SUCCESS, 
                str(_("თქვენი ელ ფოსტა დავაფიქსირე :)")))
        else:
            messages.add_message(request, messages.SUCCESS,
                str(_("თქვენი ელ.ფოსტა უკვე ჩემს ბაზაშია")))

templates/authentication/mixed_modal.html
<!-- Trigger the modal with a button -->
<button type="button" class="btn btn-info btn-lg" data-toggle="modal" data-target="#myModal">Open Modal</button>

<!-- Modal -->
<div id="myModal" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Modal Header</h4>
      </div>
      <div class="modal-body">
        <p>Some text in the modal.</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>

  </div>
</div>

templates/authentication/password.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}
  {% trans "პაროლის შეცვლა" %}
{% endblock %}

{% block content %}
  <div class="row-petite row-centered">
    <div class="page-header">
      <h3>{% trans "პაროლის შეცვლა" %}</h3>
    </div>
    <form action="." method="POST">
      {% csrf_token %}
      {% if step == 'sm' %}
        <input name="email" class="form-control" type="email" placeholder="{% trans 'თქვენი ელ.ფოსტა' %}">
      {% elif step == 'rp' %}
        <input name='password' type="password" placeholder="{% trans 'ახალი პაროლი' %}" class="form-control">
      {% endif %}
      <br>
      <button class="btn btn-default">
        {% trans "გაგრძელება" %}
      </button>
    </form>
  </div>

{% endblock %}

templates/authentication/profile.html
{% extends "base.html" %}
{% load i18n static thumbnail %}

{% block title %}
  {% trans "პროფილი" %}
{% endblock %}

{% block content %}

<div class="row">
  <div class="page-header">
    <h4>{% trans "გამარჯობა" %} {{object.get_fname}}</h4>
  </div>

  <div class="row-petite row-center">
    <form action="." method="POST">
      {% csrf_token %}
      <p><strong>{% trans "ელ.ფოსტა" %}:</strong> {{object.email}}</p><br>
      <p>
        <strong>{% trans "პაროლი" %}:</strong>
        <a href="{% url 'auth:password' %}">{% trans "პაროლის შეცვლა" %}</a>
      </p><br>
      {{updateForm.as_p}}
      <a href="{% url 'auth:signout' %}" class="btn btn-danger">
        {% trans "ვებ გვერდიდან გასვლა" %}
      </a>
      <button class="btn btn-success">
        {% trans "ინფორმაციის განახლება" %}
      </button>
    </form>
  </div>

</div>
{# END OF PROFILE INFORMATION #}

<div class="row">
  <div class="page-header">
    <h4>{% trans "კალათა" %}</h4>
  </div>


  {% if user.basket.lines.count %}
  <div class="table-responsive">
    <table class="table">
      <thead>
        <tr style="font-weight:bold;">
          <td>{% trans "პროდუქტი" %}</td>
          <td>{% trans "ვარიანტი" %}</td>
          <td>{% trans "ფასი (ერთ.)" %}</td>
          <td>{% trans "რაოდენობა" %}</td>
          <td>{% trans "წაშლა" %}</td>
        </tr>
      </thead>
      <tbody>
        {% for line in user.basket.lines.all %}
        <tr>
          <td>{{line.option.product.get_sname}}</td>
          <td>{{line.option.get_sname}}</td>
          <td>GEL{{line.option.get_price}}</td>
          <td>
            <input type="number" onclick='updateQ(this, event)' class="form-control control-min" value={{line.quantity}}
              min="0", args="{'bpk':{{user.basket.pk}}, 'opk':{{line.option.pk}}, 'newQ':NQ}">
          </td>
          <td>
            <button class="btn btn-default" onclick="ajaxable('rmfrombasket', event, callback)"
              args="{'bpk':{{user.basket.pk}}, 'opk':{{line.option.pk}}}">
              <i class="fa fa-times" aria-hidden="true"></i>
            </button>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
  {% endif %}

</div><br>

<div class="row">
  {% if user.basket.lines.count %}
    <a id="contShopping" href="{% url 'checkout:add' %}" class="btn btn-success">
      {% trans "ყიდვის დაწყება" %}
    </a>
  {% else %}
    <a class="btn btn-success" href="{% url 'shop:main' %}">
      {% trans "შეიძინე ნივთები" %}
    </a>
  {% endif %}
</div>

{% if user.order_set.count > 0 %}
<div class="row">
  <div class="page-header">
    <h4 id="orders">{% trans "ჩემი შეკვეთები" %}</h4>
  </div>

  <div class="table-responsive">
    <table class="table">
      <thead>
        <tr style="font-weight:bold;">
          <td>{% trans "პროდუქტი" %}</td>
          <td>{% trans "ვარიანტი" %}</td>
          <td>{% trans "რაოდენობა" %}</td>
          <td>{% trans "სრული ფასი" %}</td>
          <td>{% trans "სტატუსი" %}</td>
        </tr>
      </thead>
      <tbody>
        {% for order in user.order_set.all %}
        <tr>
          <td>{{order.line.option.product.get_sname}}</td>
          <td>{{order.line.option.get_sname}}</td>
          <td>{{order.line.quantity}}</td>
          <td>GEL{{order.get_price}}</td>
          <td class="ostatus{{order.status}}">{{order.get_status_display}}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>

</div>
{% endif %}

{% endblock %}

{% block scripts %}
<script>
  function callback(result, target){
    show_message(result);
    $(target).parent().parent().css("display", "none");
    if ("{{user.basket.lines.count}}" == "1")
      $("#contShopping").css("display", "none");
  }
</script>
{% endblock %}

templates/authentication/signin.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}
  {% trans "ავტორიზაცია" %}
{% endblock %}

{% block content %}

  <div class="row row-form">
    <div class="page-header">
      <h4>{% trans "ავტორიზაცია" %}</h4>
    </div>

    <form action="{% if next %}?{{next}}{% else %}.{% endif %}" method="post">
      {% csrf_token %}
      <input placeholder="{% trans 'ელ.ფოსტა' %}" class="form-control" name='email' type='email'>
      <br>
      <input placeholder="{% trans 'პაროლი' %}" class="form-control" name='password' type='password'>
      <br>
      <a href="{% url 'auth:password' %}">
        {% trans "პაროლის აღდგენა" %}
      </a>
      <br><br>
      <button id="submit" class="btn btn-success">
        {% trans "ავტორიზაცია" %}
        <i class="fa fa-chevron-right" aria-hidden="true"></i>
      </button>
      <a href="{% url 'auth:signup' %}" class="pull-right btn btn-warning">
        {% trans "რეგისტრაცია" %}
        <i class="fa fa-user" aria-hidden="true"></i>
      </a>
    </form>
  </div>

{% endblock %}